franka_teleoperation_local_node: #node name
  ros__parameters:
    inertia: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 
    # stiffness: [121.0, 121.0, 121.0,  25.0,    25.0,   25.0] 
    stiffness: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 
    damping:   [15.0, 15.0, 15.0, 5.0, 5.0, 2.0]
    robot_ip: "192.168.1.11"
