franka_teleoperation_local_node: #node name
  ros__parameters:
    inertia: [9.0, 9.0, 9.0, 16.0, 16.0, 25.0] 
    # stiffness: [121.0, 121.0, 121.0,  25.0,    25.0,   25.0] 
    stiffness: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 
    # damping:   [11.0, 11.0, 11.0, 9.0, 9.0, 9.0]
    damping:   [7.0, 7.0, 7.0, 9.0, 9.0, 11.0]
    robot_ip: "192.168.1.11"
