franka_teleoperation_local_node: #node name
  ros__parameters:
    inertia: [0.2, 0.2, 0.2, 0.2, 0.1, 0.1] 
    # stiffness: [121.0, 121.0, 121.0,  25.0,    25.0,   25.0] 
    stiffness: [30.0, 30.0, 30.0, 10.0, 10.0, 5.0] 
    damping:   [10.0, 10.0, 10.0, 7.0, 7.0, 7.0]
    robot_ip: "192.168.1.11"
