franka_teleoperation_remote_node: #node name
  ros__parameters:
    stiffness: [81.0, 81.0, 81.0, 49.0, 49.0, 49.0, 4.0] 
    damping:   [18.0, 18.0, 18.0, 14.0, 14.0, 14.0, 4.0]
    robot_ip: "192.168.1.12"
