franka_teleoperation_remote_node: #node name
  ros__parameters:
    stiffness: [25.0, 25.0, 25.0, 25.0, 16.0, 16.0, 9.0] 
    damping:   [11.0, 11.0, 11.0, 11.0, 9.0, 9.0, 7.0]
    robot_ip: "192.168.1.12"
