franka_teleoperation_local_node: #node name
  ros__parameters:
    stiffness: [81.0, 81.0, 81.0, 81.0, 81.0, 81.0, 81.0] 
    damping:   [25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0]
    robot_ip: "192.168.1.12"
